animals = [
    "Albatross",
    "Alligator",
    "Antelope",
    "Armadillo",
    "Axolotl",
    "Badger",
    "Barracuda",
    "Bat",
    "Bear",
    "Beaver",
    "Bison",
    "Boar",
    "Camel",
    "Capybara",
    "Caribou",
    "Carp",
    "Catfish",
    "Cat",
    "Chameleon",
    "Cheetah",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Chipmunk",
    "Cod",
    "Cow",
    "Coyote",
    "Crab",
    "Crayfish",
    "Crocodile",
    "Crow",
    "Deer",
    "Dog",
    "Dolphin",
    "Dove",
    "Duck",
    "Eagle",
    "Echidna",
    "Eel",
    "Elephant",
    "Elk",
    "Falcon",
    "Ferret",
    "Flamingo",
    "Fowl",
    "Fox",
    "Frog",
    "Gazelle",
    "Gecko",
    "Giraffe",
    "Goat",
    "Goose",
    "Gorilla",
    "Groundhog",
    "Guinea Pig",
    "Gull",
    "Hamster",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Hippopotamus",
    "Horse",
    "Hyena",
    "Iguana",
    "Impala",
    "Jackal",
    "Jaguar",
    "Jellyfish",
    "Kangaroo",
    "Koala",
    "Komodo Dragon",
    "Krill",
    "Lemur",
    "Leopard",
    "Lion",
    "Lizard",
    "Llama",
    "Lobster",
    "Lynx",
    "Macaw",
    "Magpie",
    "Manatee",
    "Marmot",
    "Meerkat",
    "Mockingbird",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mouse",
    "Newt",
    "Ocelot",
    "Octopus",
    "Opossums",
    "Orangutan",
    "Orca",
    "Ostrich",
    "Otter",
    "Owl",
    "Ox",
    "Panda",
    "Parrot",
    "Peacock",
    "Pelican",
    "Penguin",
    "Pig",
    "Piranha",
    "Polecat",
    "Porcupine",
    "Possum",
    "Pufferfish",
    "Rabbit",
    "Raccoon",
    "Raven",
    "Red Panda",
    "Rhinoceros",
    "Salmon",
    "Sea Lion",
    "Sea Snake",
    "Seagull",
    "Seahorse",
    "Seal",
    "Shark",
    "Sheep",
    "Shrew",
    "Skunk",
    "Sloth",
    "Slug",
    "Snake",
    "Squid",
    "Squirrel",
    "Stork",
    "Sturgeon",
    "Swordfish",
    "Tiger",
    "Toad",
    "Toucan",
    "Tortoise",
    "Tuna",
    "Turtle",
    "Vulture",
    "Walrus",
    "Weasel",
    "Whale",
    "Whale Shark",
    "Worm",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Yak",
    "Zebra"
]

countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Bahamas",
    "Bangladesh",
    "Belgium",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Brazil",
    "Bulgaria",
    "Cameroon",
    "Canada",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "England",
    "Estonia",
    "Fiji",
    "Finland",
    "France",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Guatemala",
    "Guinea",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kuwait",
    "Latvia",
    "Lebanon",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malaysia",
    "Maldives",
    "Mexico",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Niger",
    "Nigeria",
    "Northern Ireland",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "San Marino",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Somalia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sudan",
    "Sweden",
    "Switzerland",
    "Syria",
    "Thailand",
    "Tunisia",
    "Turkey",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States Of America",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Wales",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]

fruits = [
    "Apple",
    "Banana",
    "Blackberry",
    "Blueberry",
    "Cantaloupe",
    "Cherry",
    "Cranberry",
    "Dates",
    "Dragon Fruit",
    "Grapes",
    "Grapefruit",
    "Guava",
    "Honeydew Melon",
    "Kiwi",
    "Lemon",
    "Lime",
    "Mandarin",
    "Mango",
    "Nectarine",
    "Orange",
    "Papaya",
    "Passion Fruit",
    "Peach",
    "Pear",
    "Pineapple",
    "Plum",
    "Pomegranate",
    "Raspberries",
    "Star Fruit",
    "Strawberry",
    "Tangerine",
    "Watermelon"
]